[package]
name = "compute-starter-kit-static-content"
version = "0.1.0"
authors = []
edition = "2018"

[profile.release]
debug = true

[dependencies]
fastly = "0.7.1"
regex = "1.4.2"
yara = { git = "https://github.com/davbo/yara-rs", version = "0.1.0" }
